apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nocodb
  namespace: nocodb
spec:
  volumeName: pv-nocodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nocodb
  namespace: nocodb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/nocodb

    